FROM ubuntu:18.04

RUN  set -x; \
     echo "${TZ}" > /etc/timezone; \
     apt-get update -y; \
     apt-get -y --no-install-recommends install apt-utils lsof wget vim curl ca-certificates sudo unzip software-properties-common xvfb tzdata;

# Configure Java Installation
ENV JAVA_VERSION_MAJOR 8
ENV JAVA_VERSION_MINOR 251
ENV JAVA_VERSION_BUILD 08
ENV JAVA_VERSION_HASH "3d5a2bb8f8d4428bbe94aed7ec7ae784"
ENV JAVA_PACKAGE "jre"
ENV JAVA_PACKAGE_SERVER_JRE "jre"

# Install Java Server JRE
 RUN cd /tmp && \
 curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie"\
 http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/${JAVA_VERSION_HASH}/${JAVA_PACKAGE_SERVER_JRE}-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz \
 | tar -xzf - -C /opt

ENV JAVA_HOME /opt/${JAVA_PACKAGE}1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR}
ENV PATH $JAVA_HOME/bin:$PATH

# Install Ping Federate
ADD pingfederate-10.0.2.zip /opt
RUN  set -x; \
     echo "Build date: ${CACHE_DATE}" &&  \
     ls -la &&  \
     cd /opt &&  \
     unzip -d . pingfederate-10.0.2.zip &&  \
     rm ./pingfederate-10.0.2.zip &&  \
     set +x

COPY pingfederate.lic /opt/pingfederate-10.0.2/pingfederate/server/default/conf/pingfederate.lic
COPY ojdbc6-11.2.0.2.0.jar /opt/pingfederate-10.0.2/pingfederate/server/default/lib/ojdbc6-11.2.0.2.0.jar
COPY ojdbc6.jar /opt/pingfederate-10.0.2/pingfederate/server/default/lib/ojdbc6.jar

EXPOSE 9999
EXPOSE 7600
EXPOSE 7700

# Execute run script
CMD [ "/bin/bash", "-c", "/opt/pingfederate-10.0.2/pingfederate/bin/run.sh" ]
#
# Testing shell login
#
#ENTRYPOINT ["/bin/bash"]
